### ISSUE TITLE
Support for family 23 processors

### ISSUE THREAD

**Issue by devurandom** [tud-zih-energy/FIRESTARTER#15]
It would be nice if Firestarter would support family 23 processors (version 1.7.1 issues a warning that these are not supported). In particular, I have a `family 23, model 17, stepping 0` processor (AMD Ryzen 5 2400G).

**Comment by devurandom** [comment]
P.S. Firestarter misdetects the number of cores per package (8 instead of 4) and threads per core (1 instead of 2). `/proc/cpuinfo` contains the correct information (`core id` and `cpu cores`), though.

**Comment by rschoene** [comment]
Unfortunately, we do not have access to a Ryzen yet (We expect a Ryzen server to arrive soon).
Could you provide me with a copy of your `/sys/devices/system/cpu/` as tar.gz? That would make the debugging work significantly easier.

**Comment by devurandom** [comment]
Please excuse the delay. The system in question is extremely unstable, which required me to run data recovery on the disks and then try to isolate the offending devices [1].

This is the contents of /sys/devices/system/cpu/ as linux-4.16.0-0.rc4.git0.1.fc28.x86_64 (Fedora 28 Workstation Live nightly) presents it: [linux-4.16.0-0.rc4.git0.1.fc28.x86_64-sys-devices-system-cpu.tar.xz.zip](https://github.com/tud-zih-energy/FIRESTARTER/files/1845227/linux-4.16.0-0.rc4.git0.1.fc28.x86_64-sys-devices-system-cpu.tar.xz.zip) (I had to wrap the xz-compressed tarball into a zip container, to make GitHub happy.)

[1]: Still not finished, but it appears to be I/O related and not caused by CPU or RAM. Trying Google's Stressful Application Test on the disks next...

**Comment by rschoene** [comment]
Sorry for the delay,
After getting hands on a Zen Server processor, we started developing a branch ([zen](/tud-zih-energy/FIRESTARTER/tree/zen)), which should fix both issues.

**Comment by marenz2569** [comment]
Hello @devurandom,
We have just released [version 1.7.4](https://github.com/tud-zih-energy/FIRESTARTER/tree/v1.7.4). It has support for Processor family 23 model 17.
