### ISSUE TITLE
The pre-built Firestarter 1.7.1 binary shows its version as 1.6

### ISSUE THREAD

**Issue by devurandom** [tud-zih-energy/FIRESTARTER#16]
When running the pre-built binary in the Firestarter 1.7.1 package, it reports its version as "..., Version 1.6, build: 2017-10-19" on startup.

**Comment by rschoene** [comment]
Thanks for the feedback. We'll fix the version string with 1.7.2.

**Comment by rschoene** [comment]
It's fixed in 1.7.2
