### ISSUE TITLE
MacOS support doesn't work

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/FIRESTARTER#23]
There are many issues, starting with the build:

- It seems, MacOS has gotten a `clock_gettime` symbol in the meantime
- This inline asm doesn't work in generic.c: `<inline asm>:1:1: error: unknown directive
.symver memcpy, memcpy@GLIBC_2.2.5`
- `watchdog.c:105:27: error: use of undeclared identifier 'info'
      mach_timebase_info(&info);`
- `ld: library not found for -lrt`

When you finally get it to build, it SegFaults here:
```
frame #1: 0x00000001000044b6 FIRESTARTER`generic_cache_shared(cpu=0, id=0) at generic.c:973:11
   970 	    beg = strstr(tmp,",")+1;
   971 	    if (beg == NULL) return -1;
   972 	    else beg++;
-> 973 	    end = strstr(beg,",")+1;
   974 	    if (end == NULL) return -1;
   975 	    else end++;
   976 	    beg = end;
(lldb) p beg
(char *) $0 = 0x0000000000000002 ""
```

Looks like there is a missing check for the return value of seven calls to `generic_cache_info`.
This function in turn will never work on MacOS, because it's trying to read from the sysfs.

**Comment by rschoene** [comment]
@bmario You might want to try branch fix_issue_23

**Comment by bmario** [comment]
Building now works, but still the same SegFault at runtime.
