### ISSUE TITLE
Intel m7-6Y75 misses AVX512

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/FIRESTARTER#24]
While [this processor](https://ark.intel.com/content/www/us/en/ark/products/88199/intel-core-m7-6y75-processor-4m-cache-up-to-3-10-ghz.html) is a SkyLake, it only supports the following vector extensions

> Intel® SSE4.1, Intel® SSE4.2, Intel® AVX2

But the code_generator uses the AVX512_functions.c file.

**Comment by rschoene** [comment]
The code-generator creates a binary that is not microarchitecture-specific. The decision, which function will be executed is made at runtime. Therefore, this is expected behavior. However, the README might list the prerequsites (Python version, C compiler that supports AVX-512, ...).
