### ISSUE TITLE
Tag content changed - v1.7.4

### ISSUE THREAD

**Issue by tokudan** [tud-zih-energy/FIRESTARTER#26]
Was the tag v1.7.4 republished after October 2019?
Nix suddenly throws a build error, as seen in https://github.com/NixOS/nixpkgs/issues/91866.
This should only happen if the contents behind the tag changes.

**Comment by marenz2569** [comment]
Dear @tokudan,
the tag v1.7.4 has been changed after October 2019. It was not published for long as it snug its way into a commit. There have been no public releases marked on Github or our [website](https://tu-dresden.de/zih/firestarter/). I have talked to the maintainer for the firestarter packet in the NixOS organisation. I will make a pull request to fix this problem.
