### ISSUE TITLE
Coffee Lake support?

### ISSUE THREAD

**Issue by farizadp** [tud-zih-energy/FIRESTARTER#28]
Hi, I have a system with Intel Coffee Lake CPU. When running firestarter it gives:
```
Warning: GenuineIntel family 6, model 158 is not supported by this version of FIRESTARTER! Check project website for updates.
Warning: using function FUNC_HSW_COREI_FMA_2T as fallback. You can use the parameter
```
Should I concern with these warnings?

**Comment by rschoene** [comment]
You shouldn't be concerned. It might not squeeze out the last final bits, but it should provide a very high load (esp. with Turbo enabled).

**Comment by rschoene** [comment]
Due to a lack of resources for implementing a special coffee lake version and the age of this issue, i close it
