### ISSUE TITLE
Allow setting of _FIRESTARTER_VERSION_STRING/YEAR

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-energy/FIRESTARTER#31]
For the non-git build (e.g. EasyBuild) it is useful to be able to specify the VERSION vars via the CMake commandline, i.e. `-D_FIRESTARTER_VERSION_STRING=...`

All that is require is to convert the `set` to an `option` at https://github.com/tud-zih-energy/FIRESTARTER/blob/ed58e0a6e35ad84d47f139e4ecbeb252a7abb1ac/CMakeLists.txt#L32

**Comment by rschoene** [comment]
I would still like to have some information appended so that it is visible that the version is not officially 2024 / 2.1.
I would suggest an additional _FIRESTARTER_BUILD_TEMPERED variable that will add another output and that you can ignore if you want. Ok with that?

**Comment by rschoene** [comment]
(see branch optionize_year)

**Comment by Flamefire** [comment]
In the use case of EasyBuild we'd very likely download an official/tagged version but as a tarball, not as a git checkout. So the version & year would be accurate (if done correctly) which might make the message a bit confusing. Of course someone might make a mistake when writing the build config file in which case the message would be ok.

Just for context. Thanks for tackling this.
