### ISSUE TITLE
A6000 problem

### ISSUE THREAD

**Issue by DiDu0815** [tud-zih-energy/FIRESTARTER#34]
Lately, getting following error when trying to run FIRESTARTER_CUDA or FIRESTARTER_CUDA_ONLY:
```
graphics processor characteristics:
Error: CUDA error at /home/admin/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:356: error code = 700 (CUDA_ERROR_ILLEGAL_ADDRESS), device index: 0
Error: CUBLAS error at /home/admin/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:311: error code = 1 (CUBLAS_STATUS_NOT_INITIALIZED), device index: 1
```
It is a Ubuntu 20.04 system with 1x or 2x RTX A6000. 1x or 2x Quadro RTX 6000 in the same setup run fine though. First, I thought only 64GB system RAM would be the reason, but problem reoccurred even after doubling the system RAM.

[GPU_BURN](https://github.com/wilicc/gpu-burn) latest release however runs well on A6000.

**Comment by rschoene** [comment]
Dear @DiDu0815 , could you add the full output of FIRESTARTER, so that we have a little more information about the configuration that FIRESTARTER read during initialization. Thanks.

**Comment by DiDu0815** [comment]
Here is what I got with ./FIRESTARTER_CUDA --debug > debug.log
If you need something else please let me know.
[debug.log](https://github.com/tud-zih-energy/FIRESTARTER/files/8152105/debug.log)

**Comment by rschoene** [comment]
Hi @DiDu0815 , I created a branch, which should help me figure out where the first error came from (which hopefully then explains the second error). Please check it out and send me the new (more comprehensive) log:
```
git clone https://github.com/tud-zih-energy/FIRESTARTER.git
cd FIRESTARTER
git checkout origin/fix_and_new_debug
mkdir build
cd build
cmake .. -D FIRESTARTER_BUILD_TYPE=FIRESTARTER_CUDA
make
cd src
./FIRESTARTER_CUDA --debug > debug.log
```

**Comment by DiDu0815** [comment]
`Debug: Initializing CUDA matrices a, b on device nr. 0. Using -1567621120 elements of size 0 `

See attached [debug.log](https://github.com/tud-zih-energy/FIRESTARTER/files/8167550/debug.log)

**Comment by rschoene** [comment]
Could you check whether it works if you specify a specific matrix size (`-m` parameter). It seems tat there might be an overflow, which could be circumvented. You can also try to checkout the current branch, which might fix the overflow.

**Comment by DiDu0815** [comment]
I thought `-m` relates to CPU, not GPU, because also being a parameter for the basic `FIRESTARTER`.
If it relates to GPU too, what `-m` value range do you recommend to experiment with?
I'm not really a git hero - "checkout the current branch" means `git checkout master`?

**Comment by rschoene** [comment]
@DiDu0815 sorry that I was not more specific.
First, when a smaller matrix doesn't work I am afraid that the fix will probably not work. However, I added more debug stuff. The easiest way to build/run it would be to just delete the branch you checked out before and repeat the procedure from above. With the call below, `debug.log` will also contain anything written to the error stream (`2>&1`), which might help as well:
```
git clone https://github.com/tud-zih-energy/FIRESTARTER.git
cd FIRESTARTER
git checkout origin/fix_and_new_debug
mkdir build
cd build
cmake .. -D FIRESTARTER_BUILD_TYPE=FIRESTARTER_CUDA
make
cd src
./FIRESTARTER_CUDA --debug 2>&1 > debug.log
```

**Comment by DiDu0815** [comment]
@rschoene Always a pleasure to follow precise instructions :-)
Unfortunately, build was not successful this time. `make` stopped at 98%. See attachment.
[make_console.log](https://github.com/tud-zih-energy/FIRESTARTER/files/8181313/make_console.log)

**Comment by rschoene** [comment]
Hi, I fixed a bug in the latest commit of the branch. Please repeat the usual instructions for getting/compiling/running.
I'm not sure whether this is "your bug", i.e. issue #34, but let's cross fingers.

**Comment by DiDu0815** [comment]
I followed the getting/compiling/running instructions in https://github.com/tud-zih-energy/FIRESTARTER/issues/34#issuecomment-1057793487. After successful build, the executed command was: `./FIRESTARTER_CUDA --debug 2>&1 > debug.log`. The console messages after execution were the same as in my previous comment. File [debug.log](https://github.com/tud-zih-energy/FIRESTARTER/files/8223631/debug.log) attached.

Worth to mention that fault does not happen immediately, but after a few seconds of successful execution. Following a screenshot of `nvtop` running simultaneously:

![screenshot](https://user-images.githubusercontent.com/4533873/157670884-a39ff55f-fdeb-4fa1-bc18-a8adc839997f.png)

**Comment by MarkusVelten** [comment]
Dear @DiDu0815 , could you please provide us with the driver version number (via ```nvidia-smi```) and the CUDA version number (e.g., via ```nvcc --version```; the ```nvidia-smi``` output may differ, depending on your system setup)? Additionally, if you/your admins installed cuBLAS manually, please provide its version number as well. This may help us with the recreation of this issue.

If your CUDA/cuBLAS version is below 11.1, you might consider an upgrade, as 11.1 [fixed an out of bounds error in ```cublasSgemm()```](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cublas-11.1.0). We are, however, not certain if this is indeed the issue here, especially as you reported that GPU_BURN works, which uses ```cublasSgemm()``` as well.

I will create a minimal sample code that should cover the relevant aspects of the FIRESTARTER_CUDA code, which we can use to further determine the cause of this issue. This will, however, take some time as I will not have time for this during the next week.

**Comment by DiDu0815** [comment]
@MarkusVelten Thank you for taking over. CUDA and driver have been installed and updated using [official "deb (network)" method](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network). So it should be version 11.6 Update 1, for both on the machine the binaries are compiled on, and on the test machine. [system_info.txt](https://github.com/tud-zih-energy/FIRESTARTER/files/8232674/system_info.txt)

**Comment by DiDu0815** [comment]
Dear @MarkusVelten, what exactly did "will take some time" mean? It would be a pleasure for me to assist, right after getting the mentioned minimal sample code.

**Comment by MarkusVelten** [comment]
Dear @DiDu0815 , while working on the minimal sample, we discovered the likely source of the issue. Instead of sending you the minimal sample, I fixed the Firestarter-code. Please pull the latest version, rebuild and rerun it:
```bash
git clone https://github.com/tud-zih-energy/FIRESTARTER.git
cd FIRESTARTER
git checkout origin/fix_and_new_debug
mkdir build
cd build
cmake .. -D FIRESTARTER_BUILD_TYPE=FIRESTARTER_CUDA
make
cd src
./FIRESTARTER_CUDA --debug 2>&1 > debug.log
```
If the issue persists, please send us the new debug log.

**Comment by DiDu0815** [comment]
Dear @MarkusVelten, using the new build, the error is gone now; thank you for your support.
Attached the debug.log of a 60s run `./FIRESTARTER_CUDA --debug -t 60 2>&1 > debug.log`
[debug.log](https://github.com/tud-zih-energy/FIRESTARTER/files/8713786/debug.log)
