### ISSUE TITLE
Support for AMD Instinct Accelerators

### ISSUE THREAD

**Issue by nicolas-tallet** [tud-zih-energy/FIRESTARTER#51]
Is there any chance that support for AMD Instinct accelerators might be added in a near future?

**Comment by rschoene** [comment]
You can see updates in the branch [merge-amdgpu](https://github.com/tud-zih-energy/FIRESTARTER/tree/merge-amdgpu)

**Comment by rschoene** [comment]
If you want, you can try it out. I would like to have an external feedback for the current state of the tree. It currently builds in the pipeline and runs on our M210 system.

**Comment by rschoene** [comment]
Finalized with #66
