### ISSUE TITLE
Support for CUDA 12

### ISSUE THREAD

**Issue by nicolas-tallet** [tud-zih-energy/FIRESTARTER#52]
We have made an attempt to recompile FIRESTARTER using CUDA 12 but we have been unable to manage producing a functional binary.
Is it expected?
Does the current version of the code support CUDA 12?
If not, is there any chance that a CUDA 12-compliant version of FIRESTARTER will be published soon?
Thanks in advance.

**Comment by MarkusVelten** [comment]
Hi @nicolas-tallet, can you please provide a few more details? E.g., which OS version did you use, what GPU, GPU driver version, exact CUDA or NVIDIA HPC SDK version?
I recently built FIRESTARTER using CUDA 12 on one of our systems and it worked fine out of the box. No modifications to the code or CMake files were needed.

**Comment by nicolas-tallet** [comment]
Hi @MarkusVelten, thanks for your reply.

Actually, I haven't been the one trying to compile FIRESTARTER with CUDA 12, so let me bring @puddua into the conversation so that he can share the details of the issues he has faced recently.

A quick summary of the target environment, in the meantime:
- RHEL 9.1
- NVIDIA H100
- CUDA 12.2
- CUDA Driver 535.86.10

**Comment by nicolas-tallet** [comment]
Hi @MarkusVelten, after exchanging with @puddua:
- It appears that I have mistakenly reported that our issue was linked to producing a binary, which is incorrect: compilation was happening fine.
- However, the binary was generating a segmentation fault on the customer platform we have been working on.
- We have built a new binary on a distinct (but entirely similar) platform and we could successfully complete FIRESTARTER runs.
- We have no valid explanation at this time but that confirms your statement that FIRESTARTER can be successfully built with CUDA 12 out-of-the-box.

Thanks for your support.
